- server/data/languages.json
- server/data/words/hindi.json
I've updated the format as suggested. This closes #2.
> Updated JSON format of the Hindi translation

- client/package.json
- client/src/manifest.json
- client/src/store/index.js
- client/src/views/Options.vue
- Increase languages count to six
- Reset daily data upon clicking save
> Feature/v1.0.5 - Small Improvements

- server/data/quotes.json
> Add new quote by Roger Bacon

- server/data/quotes.json
added quote by Gaston Bachelard, Edmund De Waal, and Ludwig Wittgenstein
#13
> Added 3 new quotes

- server/data/quotes.json
Hi @jayehernandez great project you have here! I like how beginner friendly it is. I've added one new quote for #13.
> New Quote By Safir Kassim Boudjelal

- server/data/quotes.json
- :ballot_box_with_check:  The quote(s) added are not :x: duplicates.
- :ballot_box_with_check: The quote(s) added are about **learning a foreign language**.
- :ballot_box_with_check: The sentence attribute does not have inner quotation marks, and is ended with a period.
- :ballot_box_with_check: Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
This is for the #13 
Great project!
> Addition of Two Quotes

- server/data/words/filipino.json
related to #52 
#OpenSourceSunday
> Add second batch of Filipino words

- server/data/words/filipino.json
Related to #52 
#OpenSourceSunday
> Add 3rd batch of Filipino Language

- server/data/words/filipino.json
Related to #52 
#OpenSourceSunday
> Add fourth batch of Filipino words

- server/data/words/filipino.json
related to #52 
#OpenSourceSunday
> data(update): add more Filipino words

- server/data/languages.json
- server/data/words/indonesian.json
- :ballot_box_with_check: There is ❌ no assigned issue or pull request for this new language.
- :ballot_box_with_check: ➕ Added a new JSON object in the `server/data/languages.json` file.
- :ballot_box_with_check: Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- :ballot_box_with_check: Added the **flag** 🏳 atrribute in the format of the twemoji-awesome CSS syntax.
- :ballot_box_with_check: ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- :ballot_box_with_check: Removed duplicates and noted 🗒 them in the Pull Request.
Issue #47
> Indonesian Language Addition

- server/data/quotes.json
> Added quote by Rumi

- client/src/style/app.scss
- client/src/views/Word.vue
- server/data/words/japanese.json
- server/data/words/korean.json
I incorporated your comments :) Added romanization in Korean and Japanese.
closes #55
> romanization(feat): add romanization of the word above

- server/data/quotes.json
Hi this is my first contribution to open source project, please consider my pull request.
> added a new quote

- server/data/quotes.json
Hi I added a new quote in the quotes.json file.
I ticked all the boxes on the checklist so hope everything is ok, as this is my first contribution to an open source project. :)
> Added Kato Lomb quote

- server/data/quotes.json
Hi Jay,
I added a quote about language learning by Richard Riley.  I realized (after the fact)that I had left a "," at the bottom where it was originally typed in, so I removed it and then pushed the corrected file.
Thank you for opening up your project to allow for "newbies" to practice.  I really appreciate the opportunity to practice!!
Stacy
> Added a quote by Richard Riley

- client/package-lock.json
- client/src/views/Time.vue
We don't need to refresh the page to get the updated time. It's synchronised! 
This PR refers to [this card](https://github.com/jayehernandez/letra-extension/projects/1#card-38630812).
> Fixed automatic date and time changes

- server/data/quotes.json
> Add new quote by William Butler Yeats 

- server/data/languages.json
- server/data/words/chinese-simplified.json
New language Chinese (Simplified) with ~3000 word list.
Words either duplicated / no direct translation / not quite happy with the default google translate:
"beginning"
"technique"
"upon"
"upper"
"vs"
"whom"
"wooden"
"your"
> Added new language Chinese (Simplified)

- server/data/words/french.json
- server/data/words/german.json
- server/data/words/hindi.json
- server/data/words/indonesian.json
- server/data/words/japanese.json
- server/data/words/korean.json
- server/data/words/spanish.json
Clean-up of "true" and "false" translations in various JSON files
> #119 Clean-up of JSON files

- server/data/quotes.json
Hi! I've added a new quote into quotes.json and my profile into .allcontributorsrc. #13
> Add a new quote :) #13

- server/data/quotes.json
I added a new quote that is about learning a new foreign language.
> added new quote

- server/data/quotes.json
As per issue #13 !
(sorry, got number wrong in the commit message 😅)
> Added five new quotes

- server/data/languages.json
- server/data/words/brazilian-portuguese.json
Will add 3k words in Brazilian Portuguese
> Will add a new language

- server/data/quotes.json
Additional Noam Chomsky quote added - thank you for putting this out there!
> added an additional quote

- server/data/languages.json
- server/data/words/arabic.json
Followed instruction and removed the following from the final result:
1- "a" (article) due to not being used in Arabic.
2-  "application" due to having same meaning with "apply" (duplicate).
Thanks.
> Arabic Language 

- server/data/quotes.json
Adding great new quotes by today's phenomenal women polyglots.
> New Quotes

- server/data/quotes.json
All checks complete. File validity checked.
> Added new quote in quotes.json

- server/test/app.test.js
Adding Unit Test for server/app
Following #124
> Add test for server/app.js

- server/data/quotes.json
https://www.brainyquote.com/quotes/charles_baudelaire_397112
> Added quote by Charles Baudelaire

- server/data/quotes.json
helloooooooo first contrib wahooo
> Added more quotes! yey

- server/data/quotes.json
Removed the white space in :
"sentence": "Language is a system of signs expressive of ideas.",
> Removed White Space

- docs/new_quote.md
- server/data/quotes.json
- Sorted quotes.json using https://novicelab.org/jsonabc/ to prevent checking and addition of new quotes duplicates
- Modified Adding Quote Example according to new JSON structure and updated checklist in docs/new_quote.md
> Sorted quotes.json major update

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- client/src/store/index.js
- docs/new_language.md
- server/data/languages.json
@jayehernandez kindly review all changes and update .github/PULL_REQUEST_TEMPLATE/pull_request_template.md according to requirements.
> Create pull request template, sorted languages.json, Update new_language.md, update client/src/store/index.js

- server/data/quotes.json
> Added a quote in quotes.json

- client/package-lock.json
- client/package.json
- client/src/main.js
- client/src/views/Options.vue
A very long overdue PR for #69 and #210. Worked with @Kvaibhav01 on this. Changes included in PR:
1. Add snackbar when settings change for language selection
2. Clicking outside the options panel will also close it automatically
> Settings Pane Improvements

- server/data/quotes.json
> Added a quote

- server/data/quotes.json
@jayehernandez , I have added St. Augistine's quote #13
> Update quotes.json added St. Augistine's quote

- README.md
- client/src/store/index.js
- docs/supported_voices.md
- server/data/languages.json
- server/data/words/bangla.json
> Added Bangla language

- server/data/quotes.json
This is my first ever contribution, hope I was able to help out and did this correctly! (This PR references #13 )
> Add new quote by Frank Smith

- server/data/quotes.json
> Added quote from Confucius

- server/data/quotes.json
> Added Quotes

- server/data/quotes.json
Added quote, by Carl Theodor Körner (1791 – 1813, German poet and soldier)
> Added Quote

- server/data/quotes.json
> Add new quote by Jules Michelet

- server/test/quotes.test.js
enable checking for duplicate quotes with different letter case
resolve issue #276
> Update testing for duplicate quotes

- server/data/quotes.json
> add new quote by jhumpa lahiri

- README.md
> right bangla flag icon in readme

- .github/workflows/automerge.yml
I need help merging the PRs created by this bot automatically. Hope this works in one try!!
> Automerge PRs coming from the all-contributors bot

- server/data/quotes.json
added 3 new quotes related to language in alphabetical order
> doc: update quotes.json

- server/data/quotes.json
> added a new quote by George Orwell

- server/data/quotes.json
> Added a new quote in quotes.json file

- server/data/quotes.json
`Going to a country where you don't speak the language is like wading into the sea when you can't swim - it's intimidating at first, not impossible, and ultimately manageable.`
This PR is for #13
> Adding quote from Stewart Stafford

- server/data/quotes.json
> Added a unique quote in the quotes.json file 

- client/src/style/options.scss
changed .options-menu z-index from 2 to 4
> fixed z index of .options-menu

- server/data/quotes.json
- [x ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x ] The quote(s) added are about **learning a foreign language**.
- [x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> new quote added

- server/data/quotes.json
> Added new quote and removed violated quote

- server/data/quotes.json
> Add new quote by Tom Reynolds

- server/data/quotes.json
> Added motivation quote to travel

- server/data/quotes.json
> Added quote on Margaret Atwood

- server/data/quotes.json
> Add new quote by Johann Wolfgang von Goethe

- server/data/quotes.json
> Add new quote by Stephen D. Krashen

- server/data/quotes.json
- [x ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ x] The quote(s) added are about **learning a foreign language**.
- [ x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> Added quote from Marianna Pascal

- server/data/quotes.json
> Quotes From  Antonio Gramsci

- server/data/quotes.json
Added a quote by Anne Sexton and added a missing period to another quote.
> Updated quotes.json

- server/data/quotes.json
> Another Quotes From Kató Lomb

- server/data/words/japanese.json
updated japanese.json with some romanization
> update japanese.json: added romanization

- server/data/quotes.json
> add new quote

- server/data/quotes.json
Hello,
Added two quotes from french authors, Ferdinand de Saussure and Valery Giscard D'Estaing.
Hope it helps 🤷‍♂️
Have a nice day 🙏
- [ x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x ] The quote(s) added are about **learning a foreign language**.
- [x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> added quotes, french authors

- server/data/quotes.json
- [ x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ x] The quote(s) added are about **learning a foreign language**.
- [ x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> Update quotes.json. Added a single quote.

- server/data/quotes.json
> Update quotes.json : Add a quote by Anshuman

- server/data/quotes.json
> Added quote on Avril Lavigne

- server/data/quotes.json
> Added new quote by Swami Vivekananda

- client/test/src/views/Flag.test.js
Added unit test for Flag View
Test cases:
- it displays the correct flag
- it displays the correct language name
- it displays language name only when flag is on hover
Referencing test issue #124
> Add unit test for Flag view

- server/data/quotes.json
> Added a new Quote by Yehuda Amichai

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/swedish.json
#1 Related to add a language issue
> Add swedish translation

- server/data/quotes.json
> Add inspirational quotes

- server/data/quotes.json
> Add a new quote by dennislwm #13

- server/data/quotes.json
> Appended Quote

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/tamil.json
> Closes #154 - Add Tamil language

- server/data/quotes.json
Quote found using this resource: https://www.lingholic.com/top-ten-best-proverbs-language-learning/
- [X ] The quote(s) added are about **learning a foreign language**.
- [ X] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ X] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> Added a new quote 

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/polish.json
> 🇵🇱 Add Polish Language

- README.md
> Fix Thailand Flag in README.md file

- server/data/quotes.json
> Add Some Quotes about Language

- server/data/quotes.json
> added a new quote.

- server/data/words/filipino.json
> adding filipino words

- server/data/words/japanese.json
> add first batch japanese romanization

- server/data/quotes.json
- server/test/letra.test.js
Adding Unit Test for /daily api
Following #124
@jayehernandez please review
> Add test for /daily api

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/italian.json
- ✅ There is ❌ no assigned issue or pull request for this new language.
- ✅ ➕ Added a new JSON object in the `server/data/languages.json` file.
- ✅ Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- ✅ Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- ✅ Added the **romanization** attribute for appropriate languages. (There was no need for this, since this is a roman language)
- ✅ ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- ✅ Removed duplicates and noted 🗒 them in the Pull Request.
- ✅ Increment `currentLanguagesCount` in `client/src/store/index.js`
- ✅ Add new language in `README.md`
> Added italian :it: language #185

- server/data/quotes.json
> Added a quote from Ferdinand de Saussure

- server/data/quotes.json
- server/data/words/german.json
- [x ] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [x ] The quote(s) added are about **learning a foreign language**.
- [x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> Added Quote from Jane Goodall

- server/data/quotes.json
@jayehernandez Added one more quote
> Add quote by Margaret Atwood

- server/data/quotes.json
> Add a quote on language by George Steiner

- .all-contributorsrc
> README Changes

- server/data/words/japanese.json
> second batch of romanized Japanese words

- server/data/words/filipino.json
> adding another batch of Filipino words

- server/data/quotes.json
> quote added

- client/package-lock.json
- client/package.json
- client/src/main.js
- client/src/style/options.scss
- client/src/style/variables.scss
- client/src/views/Options.vue
Addresses Issue #434 
Change language options from checkboxes to multiple dropdown
Feel free to suggest any changes (especially on the colors as I wasn't too sure what to use)!
> Change languages options to use a multiple select dropdown

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/greek.json
> add greek language

- server/data/words/japanese.json
> another batch of romanized Japanese words

- server/data/quotes.json
Hey there,
I have added two new quotes about learning a new language by J.R.R. Tolkein.
Thank you.
> Added two new quotes by J.R.R. Tolkein

- server/data/quotes.json
> Added a new quote by Wong Huey Mey

- client/src/views/ErrorPage.vue
- client/test/src/views/ErrorPage.test.js
> Add tests for the ErrorPage view

- server/data/quotes.json
> add quote by Frantz Fanon

- server/data/words/filipino.json
> last batch of Filipino words

- server/data/quotes.json
> Add Friedrich Nietzsche quote

- server/data/quotes.json
Added Quote by  Melina Marchetta
- [x ] There is ❌ no assigned issue or pull request for this new language.
- [x ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [x ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [x ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [x ] Added the **romanization** attribute for appropriate languages.
- [ x] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [x ] Removed duplicates and noted 🗒 them in the Pull Request.
- [x ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [x ] Add new language in `README.md`
> Quote by  Melina Marchetta

- server/data/quotes.json
> Add new quote by Baroness von Ebner-Eschenbach

- server/data/quotes.json
Added three quotes by David Crystal. Thanks for reviewing!
> Added quotes by David Crystal

- server/data/quotes.json
> Added 3 quotes

- server/data/quotes.json
Added a quote by Johann Wolfgang von Goethe.
> Add a quote by Johann Wolfgang von Goethe

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/chinese-traditional.json
I am not sure should remove the words which have the same text but have different meaning and type.
If it should, please let me know, I will fix it.
> add Chinese (Traditional) language

- server/data/quotes.json
> Adicionando quote de Frederico Fellini

- server/data/words/japanese.json
> adding romanized Japanese words

- server/data/quotes.json
> re-arrange quotes.json alphabetically

- client/src/store/index.js
A friend recommended me this chrome extension because I'm learning Swedish,  I loved it right away ❤️ . However, even though Swedish is listed as one of the supported languages it is not available while using the extension.
After looking into the code, I noticed that everything was already in place and that the only problem was the `currentLanguagesCount`, so this very simple PR is just to enable Swedish to be used.
Seems like this counter got outdated at some point and then the languages at the bottom suffered. I know the counter helps to prevent one request to the backend but maybe at some point, we will need to find another solution to prevent this from happening again.
> Adding Swedish to the list

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/dutch.json
**Duplicates**
account
activist
adolescent
agenda
agent
ah
AIDS
album
alcohol
AM
analyst
architect
argument
arm
arrangement
aspect
assert
auto
baby
ban
band
bank
bar
basis
bed
blind
boom
bus
camera
campus
chef
Chinese
cholesterol
club
code
college
comfort
complex
computer
concept
concert
consultant
contact
context
contract
contrast
correct
correspondent
credit
crisis
criteria
despict
detail
direct
discipline
DNA
document
dominant
drug
effect
element
e-mail
exact
experiment
extra
factor
film
fit
focus
fruit
garage
gas
God
golf
hand
horizon
hotel
humor
immigrant
in
incident
instrument
Internet
interview
jet
journalist
junior
jury
land
later
lip
lot
lunch
machine
mail
maker
man
manager
media
menu
meter
minister
mm-hmm
mode
model
modern
moment
monitor
motor
museum
musical
oh
ok
online
open …
> Added Dutch language

- server/data/quotes.json
> Add quote by Louis Yako

- server/test/quotes.test.js
> add test (alphabetically ordered quotes)

- server/test/helper.test.js
Add unit test to helper module
> Add unit test to helper module

- server/data/words/japanese.json
> add another batch of romanized Japanese words

- server/data/quotes.json
> Add new quote about learning a foreign language

- server/data/quotes.json
> Added Fernando Lázaro Carreter quote - Hacktoberfest

- README.md
There's already a lot of quotes, this is in preparation for removing the issue at the end of October. :)
> Remove quotes contribution in README

- server/data/words/brazilian-portuguese.json
> improves pt-br translations

- server/data/quotes.json
- [ x ] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [ x ] The quote(s) added are about **learning a foreign language**.
- [ x ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ x ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.
> Added Michel Thomas Quote

- server/data/quotes.json
> added a new quote by Noam Chomsky

- README.md
- client/src/store/index.js
- server/data/languages.json
- server/data/words/croatian.json
> closes #418 add croatian

- client/test/src/router/index.test.js
This bumps the coverage of `router/index.js` to 100%.
> Add missing test for router

- server/data/quotes.json
I found this amazing quote by Steven Pinker and thought I'd try to get another PR in for hacktoberfest :)
> added Steven Pinker Quote

- README.md
- client/package.json
- client/src/manifest.json
- client/src/store/index.js
- client/src/style/flag.scss
- client/src/views/Flag.vue
This will be the first version available on Firefox, changes include:
- Adds a few changes to #301 (stores language chosen in chrome, and some UI changes below)
- Change version to 1.0.13
> Version 1.0.13

- server/data/words/thai.json
> Update mistranslated and untranslated Thai words.
